//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI.Resources.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMI.Resources.Global.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Cari {
            get {
                return ResourceManager.GetString("Cari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inggris.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilih Bahasa.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anggota.
        /// </summary>
        public static string MemberOf {
            get {
                return ResourceManager.GetString("MemberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasi Situs.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berita.
        /// </summary>
        public static string MenuBerita {
            get {
                return ResourceManager.GetString("MenuBerita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peristiwa.
        /// </summary>
        public static string MenuEvent {
            get {
                return ResourceManager.GetString("MenuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utama.
        /// </summary>
        public static string MenuHeadline {
            get {
                return ResourceManager.GetString("MenuHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasi.
        /// </summary>
        public static string MenuInformasi {
            get {
                return ResourceManager.GetString("MenuInformasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string MenuKategori {
            get {
                return ResourceManager.GetString("MenuKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunitas.
        /// </summary>
        public static string MenuKomunitas {
            get {
                return ResourceManager.GetString("MenuKomunitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partisipasi.
        /// </summary>
        public static string MenuPartisipasi {
            get {
                return ResourceManager.GetString("MenuPartisipasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pengaturan Situs.
        /// </summary>
        public static string MenuPengaturan {
            get {
                return ResourceManager.GetString("MenuPengaturan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siaran Pers.
        /// </summary>
        public static string MenuPR {
            get {
                return ResourceManager.GetString("MenuPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string MenuProgram {
            get {
                return ResourceManager.GetString("MenuProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulisan.
        /// </summary>
        public static string MenuTulisan {
            get {
                return ResourceManager.GetString("MenuTulisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertama.
        /// </summary>
        public static string PagingFirst {
            get {
                return ResourceManager.GetString("PagingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terakhir.
        /// </summary>
        public static string PagingLast {
            get {
                return ResourceManager.GetString("PagingLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selanjutnya.
        /// </summary>
        public static string PagingNext {
            get {
                return ResourceManager.GetString("PagingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebelumnya.
        /// </summary>
        public static string PagingPrevious {
            get {
                return ResourceManager.GetString("PagingPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palang Merah Indonesia.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
    }
}
