//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long id { get; set; }
        public string title { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public long category { get; set; }
        public System.Guid writer { get; set; }
        public string content { get; set; }
        public string image { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
