//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteInfo
    {
        public string theme { get; set; }
        public string footer { get; set; }
        public int id { get; set; }
    }
}
