//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMI.Resources.MainPageResources", typeof(MainPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasi.
        /// </summary>
        public static string AdministrationMenu {
            get {
                return ResourceManager.GetString("AdministrationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentikasi.
        /// </summary>
        public static string AuthenticationMenu {
            get {
                return ResourceManager.GetString("AuthenticationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontak.
        /// </summary>
        public static string ContactUsMenu {
            get {
                return ResourceManager.GetString("ContactUsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donasi.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keuangan.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bantuan.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awal.
        /// </summary>
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasi.
        /// </summary>
        public static string InformationMenu {
            get {
                return ResourceManager.GetString("InformationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpustakaan PMI.
        /// </summary>
        public static string LearnWithUs {
            get {
                return ResourceManager.GetString("LearnWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layanan Nasional PMI.
        /// </summary>
        public static string NationalCallCenter {
            get {
                return ResourceManager.GetString("NationalCallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berita.
        /// </summary>
        public static string NewsMenu {
            get {
                return ResourceManager.GetString("NewsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Lainnya.
        /// </summary>
        public static string OtherMenu {
            get {
                return ResourceManager.GetString("OtherMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lain-lain.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topik Kami.
        /// </summary>
        public static string OurTopic {
            get {
                return ResourceManager.GetString("OurTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebagai organisasi non-profit dan publik, kami mendukung keterbukaan administrasi. Cek laporan publik kami di:.
        /// </summary>
        public static string PublicInfoDesc {
            get {
                return ResourceManager.GetString("PublicInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasi Publik.
        /// </summary>
        public static string PublicInfoTitle {
            get {
                return ResourceManager.GetString("PublicInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Publik.
        /// </summary>
        public static string PublicMemberMenu {
            get {
                return ResourceManager.GetString("PublicMemberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelaporan.
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Kami.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berbincang dengan PMI.
        /// </summary>
        public static string TalkToUs {
            get {
                return ResourceManager.GetString("TalkToUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syarat dan Ketentuan.
        /// </summary>
        public static string TermsMenu {
            get {
                return ResourceManager.GetString("TermsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topik Panas.
        /// </summary>
        public static string WhatPeopleTalkAbout {
            get {
                return ResourceManager.GetString("WhatPeopleTalkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suara Anda.
        /// </summary>
        public static string WhatTheySaid {
            get {
                return ResourceManager.GetString("WhatTheySaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pekerjaan Kami.
        /// </summary>
        public static string WhatWeDoMenu {
            get {
                return ResourceManager.GetString("WhatWeDoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siapa Kami.
        /// </summary>
        public static string WhoWeAreMenu {
            get {
                return ResourceManager.GetString("WhoWeAreMenu", resourceCulture);
            }
        }
    }
}
