//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostAdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostAdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMI.Resources.PostAdminResources", typeof(PostAdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tampilkan.
        /// </summary>
        public static string ActionView {
            get {
                return ResourceManager.GetString("ActionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kembali ke daftar tulisan.
        /// </summary>
        public static string ButtonBackToList {
            get {
                return ResourceManager.GetString("ButtonBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus tulisan.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan Tulisan.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan Perubahan.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bersihkan Filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambar utama post (kosongkan jika tidak ada):.
        /// </summary>
        public static string LabelPostMainImage {
            get {
                return ResourceManager.GetString("LabelPostMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daftar Tulisan.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambah Tulisan Baru.
        /// </summary>
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulisan.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isi tulisan.
        /// </summary>
        public static string PostContent {
            get {
                return ResourceManager.GetString("PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waktu Penulisan.
        /// </summary>
        public static string PostCreated {
            get {
                return ResourceManager.GetString("PostCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda yakin mau menghapus.
        /// </summary>
        public static string PostDeletionMessage {
            get {
                return ResourceManager.GetString("PostDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penghapusan.
        /// </summary>
        public static string PostDeletionTitle {
            get {
                return ResourceManager.GetString("PostDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tulisan .
        /// </summary>
        public static string PostEditTitle {
            get {
                return ResourceManager.GetString("PostEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judul Berita.
        /// </summary>
        public static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pembaruan Terakhir.
        /// </summary>
        public static string PostUpdated {
            get {
                return ResourceManager.GetString("PostUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penulis.
        /// </summary>
        public static string PostWriter {
            get {
                return ResourceManager.GetString("PostWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari berdasarkan judul.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menampilkan tulisan .
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
    }
}
